# -*- coding: utf-8 -*-
"""001_notExercise_정답.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nAD4oQ9MuWggrgUseuQPaLnjJBh6efNS

# 운동을 하지 않는 이유 통계
## http://data.seoul.go.kr

# O. 한글폰트 설치 후 진행

> ## 1) 한글 폰트 설치
"""

import matplotlib.font_manager as fm

# Linux
!apt-get -qq -y install fonts-nanum > /dev/null

# Colab
fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
font = fm.FontProperties(fname = fontpath, size = 10)
# fm._rebuild()
!rm -rf ~/.cache/matplotlib -rf

"""> ## 2) <font color = 'red'>설치 후 '**런타임 다시 시작**'</font>

* 런타임 강제 종료 후 다시 시작
"""

import os

os.kill(os.getpid(), 9)

"""> ## 3) 한글 폰트 설정"""

import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm

mpl.rcParams['axes.unicode_minus'] = False

path = '/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf'
font_name = fm.FontProperties(fname = path, size = 10).get_name()
plt.rc('font', family = font_name)
# fm._rebuild()
!rm -rf ~/.cache/matplotlib -rf

"""# I. Data Preprocessing"""

import warnings
warnings.filterwarnings('ignore')

"""> ## 1) 'notExercise.xlsx' 파일 읽어오기"""

import pandas as pd

url = 'https://raw.githubusercontent.com/rusita-ai/pyData/master/notExercise.xlsx'
DF = pd.read_excel(url)

DF.head()

"""* DataFrame 정보"""

DF.info()

"""> ## 2) '기간' 열(Column) 삭제

* '기간'열(Column) 정보
"""

DF['기간'].value_counts()

"""* '기간'열(Column) <font color = 'red'>삭제"""

DF.drop(columns = '기간', inplace = True)

"""* <font color = 'red'>삭제</font> 결과 확인"""

DF.head()

"""> ## 3) 0, 23~52번(지역분류) index 삭제

* '대분류' 정보
"""

DF['대분류']

"""* 23번 ~ 52번 index <font color = 'red'>삭제"""

DF.drop(index = range(23, 53), inplace = True)

DF

"""* 0번 index <font color = 'red'>삭제"""

DF.drop(index = 0, inplace = True)

DF

"""# II. '성별' 통계

> ## 1) '성별' 데이터 추출
"""

DF_G = DF[DF['대분류'] == '성별'].copy()

DF_G

"""> ## 2) '대분류' 열(Column) 삭제"""

DF_G.drop(columns = '대분류', inplace = True)

DF_G

"""> ## 3) '분류'열(Column)을 index로 지정"""

DF_G.set_index('분류', inplace = True)

DF_G

"""> ## 4) matplotlib 시각화

explode는 그래프 사이의 거리

ax는 그래프 위치선정 4분면 생각하면됨

수업자료와 코드가 살짝 다른데 아래 코드가 간결화 시킨 것.
"""

import matplotlib.pyplot as plt

figure, ax = plt.subplots(2, 2, figsize = (10,10))


DF_G['운동을 할 충분한 시간이 없어서'].plot.pie(explode = [0, 0.02],
                                                ax = ax[0, 0],
                                                autopct = '%.1f%%')
ax[0, 0].set_title('운동을 할 충분한 시간이 없어서')
ax[0, 0].set_ylabel('')



DF_G['함께 운동을 할 사람이 없어서'].plot.pie(explode = [0, 0.02],
                                              ax = ax[0, 1],
                                              autopct = '%.1f%%')
ax[0, 1].set_title('함께 운동을 할 사람이 없어서')
ax[0, 1].set_ylabel('')


DF_G['운동을 할 만한 장소가 없어서'].plot.pie(explode = [0, 0.02],
                                              ax = ax[1, 0],
                                              autopct = '%.1f%%')
ax[1, 0].set_title('운동을 할 만한 장소가 없어서')
ax[1, 0].set_ylabel('')


DF_G['운동을 싫어해서'].plot.pie(explode = [0, 0.02],
                                 ax = ax[1, 1],
                                 autopct = '%.1f%%')
ax[1, 1].set_title('운동을 싫어해서')
ax[1, 1].set_ylabel('')

plt.show()

"""# III. '연령별' 통계

> ## 1) '연령별' 데이터 전처리
"""

DF_A = DF[DF['대분류'] == '연령별'].copy()
DF_A.drop(columns = '대분류', inplace = True)
DF_A.set_index('분류', inplace = True)

DF_A

"""> ## 2) matplotlib 시각화

nrows 행

ncols 열

아래는 1행 3열의 그래프로 표현하겠다는 뜻
"""

import matplotlib.pyplot as plt

figure, ax = plt.subplots(nrows = 1, ncols = 3, figsize = (20, 20))

explode_set = [0.02, 0.02, 0.02, 0.02, 0.02, 0.02]

DF_A['운동을 할 충분한 시간이 없어서'].plot(kind = 'pie',
                                           explode = explode_set,
                                           ax = ax[0],
                                           autopct = '%1.1f%%')
ax[0].set_title('운동을 할 충분한 시간이 없어서')
ax[0].set_ylabel('')



DF_A['함께 운동을 할 사람이 없어서'].plot(kind = 'pie',
                                         explode = explode_set,
                                         ax = ax[1],
                                         autopct = '%1.1f%%')
ax[1].set_title('함께 운동을 할 사람이 없어서')
ax[1].set_ylabel('')



DF_A['운동을 할 만한 장소가 없어서'].plot(kind = 'pie',
                                         explode = explode_set,
                                         ax = ax[2],
                                         autopct = '%1.1f%%')
ax[2].set_title('운동을 할 만한 장소가 없어서')
ax[2].set_ylabel('')

plt.show()

"""# IV. '학력별' 통계

> ## 1) '학력별' 데이터 전처리
"""

DF_V = DF[DF['대분류'] == '학력별'].copy()
DF_V.drop(columns = '대분류', inplace = True)
DF_V.set_index('분류', inplace = True)

DF_V

"""> ## 2) matplotlib 시각화"""

import matplotlib.pyplot as plt

figure, ax = plt.subplots(nrows = 1, ncols = 2, figsize = (15, 15))

explode_set = [0.02, 0.02, 0.02, 0.02]


DF_V['운동을 할 충분한 시간이 없어서'].plot(kind = 'pie',
                                           explode = explode_set,
                                           ax = ax[0],
                                           autopct = '%.1f%%')
ax[0].set_title('운동을 할 충분한 시간이 없어서')
ax[0].set_ylabel('')


DF_V['운동을 싫어해서'].plot(kind = 'pie',
                            explode = explode_set,
                            ax = ax[1],
                            autopct = '%.1f%%')
ax[1].set_title('운동을 싫어해서')
ax[1].set_ylabel('')

plt.show()

"""#
#
#
# End Of Document
#
#
#
"""