# -*- coding: utf-8 -*-
"""001_notExercise_미프.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uKbM2FM333bhavlT9AIX-v0aDG8NIF7I

# 운동을 하지 않는 이유 통계
## http://data.seoul.go.kr

# O. 한글폰트 설치 후 진행

> ## 1) 한글 폰트 설치
"""

import matplotlib.font_manager as fm

# Linux
!apt-get -qq -y install fonts-nanum > /dev/null

# Colab
fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
font = fm.FontProperties(fname = fontpath, size = 10)
# fm._rebuild()
!rm -rf ~/.cache/matplotlib -rf

"""> ## 2) <font color = 'red'>설치 후 '**런타임 다시 시작**'</font>

* 런타임 강제 종료 후 다시 시작
"""

import os

os.kill(os.getpid(), 9)

"""> ## 3) 한글 폰트 설정"""

import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm

mpl.rcParams['axes.unicode_minus'] = False

path = '/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf'
font_name = fm.FontProperties(fname = path, size = 10).get_name()
plt.rc('font', family = font_name)
# fm._rebuild()
!rm -rf ~/.cache/matplotlib -rf

"""# I. Data Preprocessing"""

import warnings
warnings.filterwarnings('ignore')

"""> ## 1) 'notExercise.xlsx' 파일 읽어오기"""

import pandas as pd

url = 'https://raw.githubusercontent.com/rusita-ai/pyData/master/notExercise.xlsx'
DF = pd.read_excel(url)

DF.head()

"""* DataFrame 정보"""



"""> ## 2) '기간' 열(Column) 삭제

* '기간'열(Column) 정보
"""



"""* '기간'열(Column) <font color = 'red'>삭제"""



"""* <font color = 'red'>삭제</font> 결과 확인"""



"""> ## 3) 0, 23~52번(지역분류) index 삭제

* '대분류' 정보
"""



"""* 23번 ~ 52번 index <font color = 'red'>삭제"""





"""* 0번 index <font color = 'red'>삭제"""





"""# II. '성별' 통계

> ## 1) '성별' 데이터 추출
"""





"""> ## 2) '대분류' 열(Column) 삭제"""





"""> ## 3) '분류'열(Column)을 index로 지정"""





"""> ## 4) matplotlib 시각화"""



"""# III. '연령별' 통계

> ## 1) '연령별' 데이터 전처리
"""





"""> ## 2) matplotlib 시각화"""



"""# IV. '학력별' 통계

> ## 1) '학력별' 데이터 전처리
"""





"""> ## 2) matplotlib 시각화"""



"""#
#
#
# The End
#
#
#
"""